baidu_appid: ''
baidu_apikey: ''
baidu_secretkey: ''
appreciate:
Real_CUGAN:
ai_detect:
img_to_music:
remove_bg:
anime_aesthetic_predict:
cartoonization:
openai_key: 
openai_api_url: 
openai_model: gpt-3.5-turbo
jianshang_model: wd14-vit-v2-git
jianshang_threshold: "0.35"
APIList: []
usingAPI: 1
baidu_translate:
  id: null
  key: null
youdao_translate:
  id: null
  key: null
